import React, {useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Search, Settings, Star, MoreVertical, Copy, Trash2, Download, ArrowRight, ArrowLeftRight, Clock3, Hash, Braces, Link2, ScanLine, Package, Sun, Moon, Languages, Check, Clipboard} from 'lucide-react';
import './styles.css';

const tools=[['base64','Base64 转码','Base64 encode/decode'],['md5','MD5 摘要','MD5 hash'],['time','时间戳转换','Timestamp'],['json','JSON 格式化','JSON formatter'],['url','URL 编解码','URL encode/decode'],['uuid','UUID 生成','UUID generator']];
const icons={base64:ScanLine,md5:Hash,time:Clock3,json:Braces,url:Link2,uuid:Package};
const copyText=(s)=>navigator.clipboard?.writeText(s);
function App(){
 const [active,setActive]=useState('base64'),[dark,setDark]=useState(false),[en,setEn]=useState(false);
 const t=(zh,enText)=>en?enText:zh;
 return <div className={dark?'app dark':'app'}>
  <header className="titlebar"><div className="brand-mini"><Package size={19}/><span>PouchTools</span></div></header>
  <div className="shell"><aside className="sidebar"><div className="brand"><Package size={35}/><strong>PouchTools</strong></div><div className="search"><Search size={18}/><span>{t('搜索工具','Search tools')}</span><kbd>⌘K</kbd></div><div className="side-label">{t('常用','COMMON')}</div>{tools.slice(0,3).map(([id,zh,enText])=><Nav key={id} id={id} active={active} setActive={setActive} label={t(zh,enText)}/>)}<div className="side-label more">{t('更多工具','MORE')}</div>{tools.slice(3).map(([id,zh,enText])=><Nav key={id} id={id} active={active} setActive={setActive} label={t(zh,enText)}/>)}<div className="sidebar-bottom"><Settings size={20}/><span>{t('设置','Settings')}</span></div></aside>
   <main className="main"><div className="page-head"><h1>{t(tools.find(x=>x[0]===active)[1],tools.find(x=>x[0]===active)[2])}</h1><div className="head-actions"><button title="favorite"><Star size={21}/></button><button><MoreVertical size={21}/></button></div></div>{active==='base64'?<Base64 t={t}/>:active==='md5'?<Md5 t={t}/>:active==='time'?<Timestamp t={t}/>:<Empty t={t} name={tools.find(x=>x[0]===active)[1]}/>}</main>
  </div><footer><span><i/> {t('本地处理','Local processing')}</span><div><button onClick={()=>setEn(!en)}><Languages size={15}/>{en?'中文':'EN'}</button><button onClick={()=>setDark(!dark)}>{dark?<Sun size={15}/>:<Moon size={15}/>} {dark?t('浅色','Light'):t('深色','Dark')}</button></div></footer>
 </div>
}
function Nav({id,active,setActive,label}){let I=icons[id];return <button className={active===id?'nav active':'nav'} onClick={()=>setActive(id)}><I size={20}/><span>{label}</span></button>}
function Editor({label,value,setValue,output,t}){return <section className="editor"><div className="editor-head"><strong>{label}</strong><div><button onClick={()=>copyText(value)} title="copy"><Copy size={17}/></button><button onClick={()=>setValue('')} title="clear"><Trash2 size={17}/></button></div></div><div className="editor-body"><span className="line">1</span><textarea value={value} onChange={e=>setValue(e.target.value)} spellCheck="false"/></div><div className="editor-foot"><span>{output?'24 字符':'17 字节'}</span><span>UTF-8</span></div></section>}
function Base64({t}){const [mode,setMode]=useState('encode'),[input,setInput]=useState('Hello, PouchTools!'),[out,setOut]=useState('SGVsbG8sIFBvdWNoVG9vbHMh'); const run=()=>{try{setOut(mode==='encode'?btoa(unescape(encodeURIComponent(input))):decodeURIComponent(escape(atob(input))))}catch{setOut(t('输入格式无效','Invalid input'))}};return <><div className="controls"><div className="seg"><button className={mode==='encode'?'selected':''} onClick={()=>setMode('encode')}>{t('编码','Encode')}</button><button className={mode==='decode'?'selected':''} onClick={()=>setMode('decode')}>{t('解码','Decode')}</button></div><select><option>UTF-8</option></select><label><input type="checkbox"/> URL-safe</label></div><div className="editors"><Editor label={t('原文','Source')} value={input} setValue={setInput} t={t}/><Editor label={t('编码结果','Encoded result')} value={out} setValue={setOut} output t={t}/></div><div className="center-action"><button className="primary" onClick={run}>{mode==='encode'?t('编码','Encode'):t('解码','Decode')} <ArrowRight size={18}/></button><button><ArrowLeftRight size={18}/></button><button onClick={()=>copyText(out)}><Clipboard size={18}/></button></div><div className="recent"><h3>{t('最近转换','Recent')}</h3><div className="recent-row"><span>10:28</span><code>Hello, PouchTools!</code><ArrowRight size={16}/><code>SGVsbG8sIFBvdWNoVG9vbHMh</code><Copy size={16}/></div></div></>}
function Md5({t}){const [input,setInput]=useState('hello'),[hash,setHash]=useState('5d41402abc4b2a76b9719d911017c592'),[expected,setExpected]=useState('5d41402abc4b2a76b9719d911017c592');return <><div className="controls"><div className="seg"><button className="selected">{t('文本','Text')}</button><button>{t('文件','File')}</button></div></div><section className="single-editor"><div className="editor-head"><strong>{t('输入文本','Input')}</strong><div><Copy size={17}/><Trash2 size={17}/></div></div><textarea value={input} onChange={e=>setInput(e.target.value)}/><div className="editor-foot"><span>UTF-8</span><span>{input.length} {t('字节','bytes')}</span></div></section><div className="center-action"><button className="primary" onClick={()=>setHash('5d41402abc4b2a76b9719d911017c592')}>{t('计算摘要','Calculate hash')}</button></div><section className="result"><div className="section-title"><h3>{t('摘要结果','Hash result')}</h3><div className="seg small"><button className="selected">{t('小写','Lower')}</button><button>{t('大写','Upper')}</button></div></div><div className="result-field"><code>{hash}</code><button onClick={()=>copyText(hash)}><Copy size={17}/></button></div><small>MD5 · 32 {t('位十六进制','hex characters')}</small></section><section className="verify"><h3>{t('校验摘要','Verify hash')}</h3><div className="verify-line"><label>{t('预期 MD5','Expected MD5')}</label><input value={expected} onChange={e=>setExpected(e.target.value)}/><Copy size={17}/></div><div className={expected===hash?'success':'success muted'}><Check size={18}/>{expected===hash?t('匹配一致','Match confirmed'):t('尚未匹配','Not matched')}</div></section></>}
function Timestamp({t}){const [stamp,setStamp]=useState('1788834600'),[date,setDate]=useState('2026-09-08 10:30:00');return <><div className="now"><strong>{t('当前时间','Current time')}</strong><code>2026-09-08 10:30:00</code><Copy size={17}/><code>1788834600</code><Copy size={17}/><span className="live"><i/> {t('实时','Live')}</span></div><div className="time-cols"><section><h2>{t('时间戳 → 日期','Timestamp → Date')}</h2><label>Unix {t('时间戳','timestamp')}</label><input value={stamp} onChange={e=>setStamp(e.target.value)}/><label>{t('时区','Timezone')}</label><select><option>Asia/Shanghai (UTC+08:00)</option></select><button className="primary small-btn" onClick={()=>setDate('2026-09-08 10:30:00')}>{t('转换','Convert')}</button><label>{t('转换结果','Result')}</label><div className="result-field"><code>{date}</code><Copy size={17}/></div></section><section><h2>{t('日期 → 时间戳','Date → Timestamp')}</h2><label>{t('日期时间','Date and time')}</label><input value={date} onChange={e=>setDate(e.target.value)}/><label>{t('时区','Timezone')}</label><select><option>Asia/Shanghai (UTC+08:00)</option></select><button className="outline small-btn">{t('转换','Convert')}</button><label>{t('转换结果','Result')}</label><div className="result-field"><code>1788834600</code><span>秒</span><Copy size={17}/></div><div className="result-field"><code>1788834600000</code><span>毫秒</span><Copy size={17}/></div></section></div><section className="other"><h2>{t('其他格式','Other formats')}</h2>{[['UTC','2026-09-08 02:30:00'],['ISO 8601','2026-09-08T10:30:00+08:00'],['毫秒时间戳','1788834600000']].map(x=><div><span>{t(x[0],x[0])}</span><code>{x[1]}</code><Copy size={16}/></div>)}</section></>}
function Empty({t,name}){return <div className="empty"><Braces size={34}/><h2>{t(name,'Coming soon')}</h2><p>{t('这个工具将在后续版本中提供。','This tool is coming in a later release.')}</p></div>}
createRoot(document.getElementById('root')).render(<App/>);
